// Dump the host's entire world — intakes, characters, relationships — to a
// gitignored markdown file you can read alongside Claude Code while you
// brainstorm. This is half of the AI bridge: the app hands its data *out*; you
// draft characters in the chat; `import-characters.mjs` takes the drafts back.
//
// Usage:  node scripts/export-world.mjs "<your host passcode>"
//   (or)  HOST_PASSCODE="..." node scripts/export-world.mjs
//   (or)  npm run export:world -- "<passcode>"
//
// Writes to planning/world.md (gitignored — it contains real people's answers).
import { createClient } from '@supabase/supabase-js';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const passcode = process.argv[2] || process.env.HOST_PASSCODE;
if (!passcode) {
  console.error('Pass your host passcode: npm run export:world -- "<passcode>"');
  process.exit(1);
}

const env = Object.fromEntries(
  readFileSync(new URL('../.env', import.meta.url), 'utf8')
    .split('\n').filter(Boolean).map((l) => l.split(/=(.*)/s).slice(0, 2)),
);
const sb = createClient(env.VITE_SUPABASE_URL, env.VITE_SUPABASE_ANON_KEY, {
  auth: { persistSession: false },
});

const { data: world, error } = await sb.rpc('host_bootstrap', { p_secret: passcode });
if (error) {
  console.error('host_bootstrap failed (passcode wrong, or migrations unrun?):', error.message);
  process.exit(1);
}

// ── intake digest — the fields worth brainstorming from, in a sensible order ──
const COMFORT = ['Extra', 'Cameo', 'Recurring', 'Supporting', 'Lead'];
const FIELDS = [
  ['rsvp', 'RSVP'],
  ['contact', 'Contact'],
  ['roleplay_comfort', 'Role size'],
  ['trope_wishlist', 'Tropes they want to play'],
  ['surprise_fact', 'How much of the character is them'],
  ['reveal_dial', 'Reveal dial (1 fiction → 5 themselves)'],
  ['hard_limits', 'Hard limits'],
  ['dietary', 'Dietary'],
  ['worst_job', 'Worst job'],
  ['hobby', 'Hobby'],
  ['changed_opinion', 'Changed opinion'],
  ['outable_secret', 'Outable secret'],
  ['social_known', 'Known for'],
  ['social_want', 'Wants to be seen as'],
  ['fakeable_skill', 'Fakeable skill'],
  ['public_bio', 'Public bio'],
  ['notes', 'Notes'],
];

function fmt(key, value) {
  if (value == null || value === '') return null;
  if (key === 'roleplay_comfort') {
    const cap = COMFORT[Number(value) - 1];
    return cap ? `${value} — ${cap}` : String(value);
  }
  return String(value).trim() || null;
}

function dish(p) {
  const cats = (p.dish_category ?? '').split(',').map((c) => c.trim()).filter(Boolean);
  let details = {};
  try {
    const parsed = JSON.parse(p.dish_detail || '{}');
    if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) details = parsed;
  } catch { /* legacy free-text */ if ((p.dish_detail ?? '').trim()) return p.dish_detail.trim(); }
  if (!cats.length) return Object.values(details).filter(Boolean).join(' · ') || null;
  return cats.map((c) => {
    const d = (details[c] ?? details[c.toLowerCase()] ?? '').toString().trim();
    return d ? `${c}: ${d}` : c;
  }).join(' · ') || null;
}

const charById = new Map(world.characters.map((c) => [c.id, c]));
const STAGE = (c) => (c.released ? 'full' : c.background_released ? 'consent' : 'private');

const lines = [];
const push = (s = '') => lines.push(s);

push(`# Party world`);
push();
push(`> Generated by \`scripts/export-world.mjs\`. Gitignored — contains real answers.`);
push();
if (world.settings) {
  push(`**${world.settings.party_title || 'Untitled party'}** — ${world.settings.party_blurb || ''}`.trim());
  push(`Intake ${world.settings.intake_open ? 'open' : 'closed'} · roster ${world.settings.roster_visible ? 'visible' : 'hidden'}`);
  push();
}
push(`${world.participants.length} guests · ${world.characters.length} characters · ${world.relationships.length} relationships`);
push();

// ── Guests ──
push(`## Guests`);
push();
const submitted = (p) => Boolean((p.preferred_name || '').trim() || (p.trope_wishlist || '').trim() || (p.surprise_fact || '').trim());
for (const p of world.participants) {
  const name = (p.preferred_name || '').trim() || '(no name yet)';
  const cast = p.character_id ? charById.get(p.character_id)?.name : null;
  push(`### ${name}${cast ? ` — cast as ${cast}` : ''}${submitted(p) ? '' : '  _(not submitted)_'}`);
  push(`\`participant: ${p.id}\``);
  push();
  push(`Bringing: ${dish(p) ?? '—'}`);
  for (const [key, label] of FIELDS) {
    const v = fmt(key, p[key]);
    if (v) push(`- **${label}:** ${v.replace(/\n+/g, ' / ')}`);
  }
  push();
}

// ── Characters ──
push(`## Characters`);
push();
if (!world.characters.length) push('_None yet._');
for (const c of world.characters.slice().sort((a, b) => (a.created_at ?? '').localeCompare(b.created_at ?? ''))) {
  const cast = world.participants.find((p) => p.character_id === c.id);
  push(`### ${c.name || '(unnamed)'}${c.title ? ` — ${c.title}` : ''}  \`${STAGE(c)}\``);
  push(`\`id: ${c.id}\``);
  push();
  if (cast) push(`- **Cast:** ${cast.preferred_name || '(unnamed guest)'}`);
  if (c.juice) push(`- **Juice:** ${c.juice}`);
  if (c.background) push(`- **Background:** ${c.background}`);
  if (c.act1) push(`- **Act I:** ${c.act1}`);
  if (c.act2) push(`- **Act II:** ${c.act2}`);
  if (c.act3) push(`- **Act III:** ${c.act3}`);
  if (c.action) push(`- **Action (party-time secret):** ${c.action}`);
  if (c.secret) push(`- **Secret / motive (host-only):** ${c.secret}`);
  if (c.props) push(`- **Props:** ${c.props}`);
  if (c.recommended_meets) push(`- **People to meet:** ${c.recommended_meets}`);
  if (Array.isArray(c.truth_tags) && c.truth_tags.length) {
    push(`- **Truth tags:** ${c.truth_tags.map((t) => `${t.beat ?? '?'} → ${t.truth ?? ''}`).join(' · ')}`);
  }
  push();
}

// ── Relationships ──
push(`## Relationships`);
push();
if (!world.relationships.length) push('_None yet._');
for (const r of world.relationships) {
  const a = charById.get(r.from_char)?.name ?? r.from_char;
  const b = charById.get(r.to_char)?.name ?? r.to_char;
  push(`- ${a} → ${b}${r.label ? ` : ${r.label}` : ''}`);
}
push();

mkdirSync(new URL('../planning/', import.meta.url), { recursive: true });
const out = new URL('../planning/world.md', import.meta.url);
writeFileSync(out, lines.join('\n'), 'utf8');
console.log(`Wrote planning/world.md — ${world.participants.length} guests, ${world.characters.length} characters.`);
